export const CHANGE_POSITION_START = 'CHANGE_POSITION_START'

export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCESS = 'FETCH_TASKS_SUCESS'
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_COMPLETED = 'SHOW_COMPLETED'
export const SHOW_ACTIVE = 'SHOW_ACTIVE'
export const SHOW_IMPORTANT = 'SHOW_IMPORTANT'
export const SHOW_REGULAR = 'SHOW_REGULAR'
export const SHOW_UNIPORTANT = 'SHOW_UNIPORTANT'
