export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'
export const ADD_TASK_START = 'ADD_TASK_START'
export const ADD_TASK_SUCESS = 'ADD_TASK_SUCESS'

export const REMOVE_TASK_START = 'REMOVE_TASK_START'
export const REMOVE_TASK_FAILED = 'REMOVE_TASK_FAILED'
export const REMOVE_TASK_SUCESS = 'REMOVE_TASK_SUCESS'

export const TOGGLE_COMPLETE_START = 'TOGGLE_COMPLETE_START'
export const TOGGLE_COMPLETE_FAILED = 'TOGGLE_COMPLETE_FAILED'
export const TOGGLE_COMPLETE_SUCESS = 'TOGGLE_COMPLETE_SUCESS'

export const CHANGE_TASK = 'CHANGE_TASK'

export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCESS = 'FETCH_TASKS_SUCESS'
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED'