export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'
export const ADD_TASK_START = 'ADD_TASK_START'
export const ADD_TASK_SUCESS = 'ADD_TASK_SUCESS'

export const REMOVE_TASK_START = 'REMOVE_TASK_START'
export const REMOVE_TASK_FAILED = 'REMOVE_TASK_FAILED'
export const REMOVE_TASK_SUCESS = 'REMOVE_TASK_SUCESS'

export const TOGGLE_COMPLETE_START = 'TOGGLE_COMPLETE_START'
export const TOGGLE_COMPLETE_FAILED = 'TOGGLE_COMPLETE_FAILED'
export const TOGGLE_COMPLETE_SUCESS = 'TOGGLE_COMPLETE_SUCESS'

export const CHANGE_SIGN_TASK = 'CHANGE_SIGN_TASK'

export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCESS = 'FETCH_TASKS_SUCESS'
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_COMPLETED = 'SHOW_COMPLETED'
export const SHOW_ACTIVE = 'SHOW_ACTIVE'
export const SHOW_IMPORTANT = 'SHOW_IMPORTANT'
export const SHOW_REGULAR = 'SHOW_REGULAR'
export const SHOW_UNIPORTANT = 'SHOW_UNIPORTANT'